name: Ruff
on: [ push ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          args: check --fix-only --unsafe-fixes --show-fixes
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Ruff Action -> Fixing linting errors
